version: "3.8"

services:
  irc_client:
    image: irssi_client
    build:
      context: .
      dockerfile: Dockerfile
    container_name: irssi_client
    network_mode: "host"
    command: ["/usr/sbin/inspircd", "--runasroot", "--nofork"]

# 도커 컨테이너를 올린다.
# docker compose -f docker-compose-irssi.yml up -d

#################################################
# irssi 패킷 관찰
# docker exec -it irssi_client bash 
# tcpflow port 12345 -c

# irssi 클라이언트 실행 -> 우리서버 연결
# docker exec -it irssi_client bash 
# irssi
# /connect -nocap host.docker.internal 12345 password

# nc로 수제로 연결할때
# nc host.docker.internal 12345

##################################################
# irssi 패킷 관찰
# docker exec -it irc bash
# tcpflow -i lo port 6667 -c

# irssi 클라이언트 -> 상용서버 연결
# docker exec -it irc bash
# irssi
# /connect -nocap 127.0.0.1 6667 your_password

# nc로 수제로 연결할때
# nc 127.0.0.1 6667

######################################################

# 도커 컨테이너를 내린다.
# docker compose -f docker-compose-irssi.yml down